title: JS Design Datterns
email: tche4409@gmail.com
# baseurl: 'JS-Design-Pattern' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
plugins:
  - jekyll-feed
theme: just-the-docs
theme: just-the-docs
# remote_theme: pmarsceill/just-the-docs
